### ISSUE TITLE
ei_rxc: Renaming chain columns before results table

### ISSUE THREAD

**Issue by hikari-murayama** [RPVote/eiCompare#104]
Before creating the results table for `ei_rxc`, the code tries to rename the chains to be for their specified race/candidate pair.

https://github.com/RPVote/eiCompare/blob/396a32456d41aeee9adcaf327dbd00863c60becf/R/ei_rxc.R#L294-L299

Currently Line 296 separates on a period. If a candidate in the candidate columns list is named something like "jean.pierre", their name is split and results in more column names than there are columns.

**Comment by aridf** [comment]
Closed by #105
