### ISSUE TITLE
Add platform dependency notes to README

### ISSUE THREAD

**Issue by 1beb** [RPVote/eiCompare#135]
**Is your feature request related to a problem? Please describe.**

Missing platform dependency notes in README.

**Describe the solution you'd like**

Please add a note in the README: 

The following platform dependencies may be required on Ubuntu/Debian based systems: 

```
sudo apt install libfftw3-dev fftw-dev
```

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by aridf** [comment]
Closing with most recent merge to master
