### ISSUE TITLE
Pre-Processing Data [Geocoding]: Add tests to identify non-geocoded data

### ISSUE THREAD

**Issue by jcburke** [RPVote/eiCompare#20]
- [x] Create a warning/flag for missing geocoded data. 

- [x] Identify percent of voters with geocodes that are missing.

- [x] Create tests that re-format voter addresses in order to use for forward geocoding with packages like Opencage.

- [x] Output to identify types of addresses that do not match. Assessing how geocodes may be systematically missing. 

- [x] Output a map(s) of the accuracy of geocoded

**Comment by pssachdeva** [comment]
@jcburke, this issue is finished up by you PR #66 right?

**Comment by jcburke** [comment]
Yes, I'll close this issue now.
