### ISSUE TITLE
`doParallel` not in namespace

### ISSUE THREAD

**Issue by aridf** [RPVote/eiCompare#68]
@hikari-murayama Each time I try to run `ei_iter()` I have to first run `library(doParallel)`. Otherwise I get this error: `Error in ifelse(par_compute, `%dopar%`, `%do%`) : object '%do%' not found`.  It seems like doParallel is not imported in `NAMESPACE`. 

This is a bit of an awkward spot because we're only using the operators from this package, but I think we still might need to add an `@import doParallel` or `@importFrom doParallel somefunction` somewhere.

**Comment by lorenc5** [comment]
Note that I ran into this. doParallel is listed as imported in description file. Need to sort out how to handle this. @scottyhq any suggestions in terms of dealing with an import package but that an error is still thrown. That is, doParallel is listed as an import. But you run ei_iter() without going out of your way to library(doParallel) you get this error.
