### ISSUE TITLE
ei_iter criptic parrallel error

### ISSUE THREAD

**Issue by lorenc5** [RPVote/eiCompare#77]
<img width="676" alt="Screen Shot 2020-08-13 at 2 21 33 PM" src="https://user-images.githubusercontent.com/26538598/90190333-0c48c400-dd7c-11ea-9d38-79f51a745afc.png">

R threw this error before I loaded the various parallel processing packages, when par_compute set to FALSE. Seems that user will need to have these packages loaded regardless of if they are using parallel or not? Is there a way around that? And then also can we try to throw a more communicative error specifying the packages they need to install. Or maybe that can be done at the package installation stage and include more depends (although I think we decided to avoid that)

**Comment by aridf** [comment]
I believe this is because doParellel is not in the namespace as described in this other issue #68. Should be sorted out by adding this import. A more long-term solution might be to move parallel processing to `suggests`, but this might take place down the line a bit.

**Comment by lorenc5** [comment]
In the description file, doParallel is imported. I think that means we would need to move it to depends no?

**Comment by hikari-murayama** [comment]
I tried putting `@importFrom foreach %do% %dopar%` at the top of the relevant scripts in my PR #57 which seemed to remedy this issue. In terms of making it optional, users would still need the foreach file to run it not in parallel since the %do% infix is needed in how the iteration is set up.

**Comment by lorenc5** [comment]
Maybe that line needs to go into the body of the function? 

Especially before we get to this line in the function (which is throwing the error):

    `%myinfix%` <- ifelse(par_compute, `%dopar%`, `%do%`)

**Comment by aridf** [comment]
This should be dealt with after @hikari-murayama's  merge
