### ISSUE TITLE
visualization vignette suggestions

### ISSUE THREAD

**Issue by jcburke** [RPVote/eiCompare#80]
https://github.com/RPVote/eiCompare/blob/5a436c0f5d2320425c1ec88f05eef9ceeab0d41b/vignettes/eiCompare_visualizations.Rmd#L37
Has a typo,  "avergae percentage"

**Comment by jcburke** [comment]
Has typo, "iteraative ei".

**Comment by jcburke** [comment]
The tutorial says that plot_path will be set to where the vignette lives, (suggesting that the user should change the `plot_path`, correct? If so, maybe directing the user to save their plot  for the purposes of getting output.

**Comment by jcburke** [comment]
When running `ei_iter()` and setting `plots` to `TRUE` I received the following error,
"in { : task 3 failed - "missing value where TRUE/FALSE needed"

**Comment by lorenc5** [comment]
I got a similar error in ei_iter() last week. I think it is due to the erho parameter needing to be adjusted. This is a somewhat common ei::ei() function error I've come across over the years.
